FROM golang:1.21

WORKDIR /usr/local/app
COPY . .

RUN go install github.com/cosmtrek/air@v1.49.0
RUN go install github.com/a-h/templ/cmd/templ@v0.2.501
RUN go install -tags 'mysql' github.com/golang-migrate/migrate/v4/cmd/migrate@v4.17.0
RUN go mod tidy

ENTRYPOINT [ "air" ]
CMD [ "-c", ".air.toml" ]
